baseURL = 'https://nuna.moe/'
languageCode = 'en-us'
title = 'Nuna.Moe'
[params]
  description = "A tribute to the best companions in the world."
  animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Photos"
  url = "/photos/"