baseURL = 'https://nuna.moe/'
theme = 'flashdrive'
defaultContentLanguage = 'en'

[languages.en]
  languageCode = 'en-us'
  languageName = 'English'
  title = 'FlashDrive'
  description = "A memory box."
  weight = 1
  contentDir = 'content/en'

[languages.es]
  languageCode = 'es'
  languageName = 'Espa√±ol'
  title = 'FlashDrive'
  description = "Caja de recuerdos."
  weight = 2
  contentDir = 'content/es'