baseURL = 'https://nuna.moe'
theme = 'bulletin'
defaultContentLanguage = 'en'

[languages.en]
  languageCode = 'en-us'
  languageName = 'English'
  title = 'My Bulletin Board'
  description = "A memory board."
  weight = 1
  contentDir = 'content/en'

  [[languages.en.menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[languages.en.menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 20

  [[languages.en.menus.main]]
    name = 'Tags'
    pageRef = '/tags/'
    weight = 30

[languages.es]
  languageCode = 'es'
  languageName = 'Espa√±ol'
  title = 'Mi Tablero'
  description = "Mural de recuerdos."
  weight = 2
  contentDir = 'content/es'

  [[languages.es.menus.main]]
    name = 'Inicio'
    pageRef = '/'
    weight = 10

  [[languages.es.menus.main]]
    name = 'Acerca de'
    pageRef = '/about/'
    weight = 20

  [[languages.es.menus.main]]
    name = 'Etiquetas'
    pageRef = '/tags/'
    weight = 30